# Generated by Django 5.0.6 on 2024-07-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.CharField(max_length=100)),
                ('dst_ip', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
            ],
        ),
    ]
